version: "3.9"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "8085:8080"
      - "4566-4576:4566-4576"
    environment:
      - SERVICES=${SERVICES}
      - DEFAULT_REGION=sa-east-1
      - http_proxy
      - https_proxy
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack/init-scripts:/docker-entrypoint-initaws.d
      - ./localstack/configs:/configs
      - /var/run/docker.sock:/var/run/docker.sock
      - volumelocalstack:/var/lib/localstack
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret123
      - MYSQL_DATABASE=dbvote
    volumes:
      - 'mysql:/var/lib/mysql'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    restart: always
volumes:
  volumelocalstack:
  mysql: